Added overlay click away feature.
deviap/deviap-main pull request #79
Opened 2021-02-28 19:57 UTC by u-train

This PR solves issue https://github.com/deviap/deviap-main/pull/77.

2021-03-11 23:34 UTC, Sanjay-B commented on source/application/splashscreen/main.lua
> +		if destroyed then return end
Redundant.

2021-03-11 23:35 UTC, Sanjay-B requested changes

2021-03-11 23:35 UTC, Sanjay-B commented on source/application/splashscreen/main.lua
> +	container:on("destroying", function() destroyed =true end)
Lack of proper spacing in ``=true`` is making me have a panic attack.

2021-03-12 00:31 UTC, u-train commented on source/application/splashscreen/main.lua
> +		if destroyed then return end
No, we have to check to make sure the objects aren't destroyed before we set property. If the object is destroyed and we try to set a property, it will error.

2021-03-12 00:31 UTC, u-train commented on source/application/splashscreen/main.lua
> +	container:on("destroying", function() destroyed =true end)
will fix bby

2021-04-05 03:55 UTC, Sanjay-B approved these changes

2021-04-05 03:55 UTC, merged