Constraint tabs
deviap/deviap-main pull request #8
Opened 2020-09-03 20:42 UTC by u-train

Working branch. Controllers do not have documentation nor does it have stability. Do not merge/review or I will smack you Sanjay.

--

Adds constraints to UI library. Controllers are built upon the tab constraints.

2020-09-04 06:36 UTC, Sanjay-B commented
I won't be reviewing this without proper documentation. 
``source/libraries/UI/constraints/controller.lua``

2020-09-05 03:12 UTC, Sanjay-B requested changes

2020-09-05 03:12 UTC, Sanjay-B commented on source/application/main.lua
> +--require("tevgit:source/application/updater/main.lua")
This file is not meant to have code. It's an entry point file where it also points to other main files. It should not have your test code. Test code should never make its way into production. Clean this up.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/gridLayout.lua
> +return function()
I'm confused as to what this is for. I'm assuming that this is still test a work in progress. You're requiring a module & returning an empty function. I need more context.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/horizontialLayoutAuto.lua
> +local count = function(x)
Document this. I know what it does & how it works but, if we don't document every function, our codebase will turn into a mess. Correct this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/horizontialLayoutAuto.lua
> +
Missing documentation ``@parameter`` tag. Fix this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/horizontialLayoutAuto.lua
> +				Refreshes the container.
Missing ``@parameter`` & ``@return`` tags. Fix this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/horizontialLayoutAuto.lua
> +					Object.
Missing ``@return`` documentation tag. Correct this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/horizontialLayoutAuto.lua
> +end;
Remove the ``;``. I shouldn't see ``;`` in your code.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalLayoutAuto.lua
> +
Missing ``@parameter`` documentation tag. Fix this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalLayoutAuto.lua
> +		]]
Missing ``@parameter`` & ``@return`` documentation tags. Fix this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalLayoutAuto.lua
> +			object:destroy()
If you're destroying the object's children & then the object, just destroy the object & kill two birds with one stone.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalLayoutAuto.lua
> +					Object.
Missing ``@return`` documentation tag. Fix it.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalLayoutAuto.lua
> +end;
Remove ``;``. I shouldn't see ``;`` in your code.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalNavLayout.lua
> +		]]
Missing ``@parameter`` & ``@return`` documentation tags. Fix it.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalNavLayout.lua
> +			object:destroy()
Refer to the other comment made about this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalNavLayout.lua
> +				Refreshes the layout.
Missing ``@parameter`` & ``@return`` documentation tags. Correct this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/verticalNavLayout.lua
> +			object:destroy()
Refer to the last two comments made about this.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +	public.tabs = { x = {}; y = {} }
Remove ``;`` & replace with a ``,``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			min = min;
Remove ``;`` & replace with a ``,``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			max = max;
Remove ``;`` & replace with a ``,``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			weight = weight;
Remove ``;`` & replace with a ``,``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			tag = tag;
Remove ``;``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			tag = tag;
Remove ``;`` & replace with a ``,``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			offset = offset;
Remove ``;`` & replace with a ``,``. I should never see a ``;``.

2020-09-05 03:12 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			relativeTabs = {};
Remove ``;``. I should never see a ``;``.

2020-09-05 03:51 UTC, u-train commented on source/libraries/UI/constraints/controllers/gridLayout.lua
> +return function()
Unimplemented.

2020-09-05 04:21 UTC, u-train commented on source/libraries/UI/constraints/tabResolver.lua
> +			weight = weight;
Why must you be attacking the colon character?

2020-09-07 23:25 UTC, Sanjay-B commented on source/libraries/UI/constraints/controllers/gridLayout.lua
> +return function()
We need this. Implement it.

2020-09-07 23:26 UTC, Sanjay-B commented on source/libraries/UI/constraints/tabResolver.lua
> +			weight = weight;
This Lua & not Java. ``;`` don't match the majority of the codebase. Looking for consistency not personal preference.

2020-09-08 16:36 UTC, Sanjay-B approved these changes

2020-09-08 16:36 UTC, merged