Add enum system
deviap/deviap-main pull request #9
Opened 2020-09-04 01:05 UTC by thenerdie

Man I'm so uninvolved oh my god

Pull request after 2 weeks = 39 fucking lines of code

2020-09-04 19:10 UTC, Sanjay-B commented
You're merging this into the wrong branch. The merge branch should be ``development``. I've corrected it for you.

2020-09-04 19:11 UTC, Sanjay-B commented
You're merging this into the wrong branch. The merge branch should be development. Please change it to the correct branch before I review.

2020-09-04 19:30 UTC, thenerdie commented
XDXD LOL ficxed!!121

2020-09-05 02:50 UTC, Sanjay-B requested changes

2020-09-05 02:50 UTC, Sanjay-B commented on source/libraries/UI/enum.lua
> +
You need to document your code. Nothing here is documented. Even if it's straight-forward. 

I need to see two things: 
A). Documentation for what each & every method does. Refer to the other pull requests for the format. 

B). A solid example of this in the works. Something basic but, good enough for me to understand the design & flow of this system.

2020-09-08 01:00 UTC, thenerdie commented
this should work.... hopefully../.....,,;,,..

2020-09-08 01:01 UTC, thenerdie commented on source/libraries/UI/enum.lua
> +
I think I did this...

2020-09-08 16:31 UTC, Sanjay-B approved these changes

2020-09-08 16:33 UTC, merged

2020-10-07 01:54 UTC, thenerdie commented
jkl; hsdfgkl;d hjfgdfglk jfjlk hdgfhgfhjgdf dgf jlkhgfjdgfl jkhdgfl j ljd jkgdfljk flj jdfgfjk dfgjk hdgfljk hfljk hgflj hkdgfljk hdgfjl gkhdfljd ghkfjldg kfhljdg khfjldg kfhjld gkfhljdfg hkljkdgh fjkl hdfgjld kfgd jlghkfd jlghkfjlhk dgfjkld hgfjld hkgfjl hkdgfjl hkgfjl hkgfjlk hgljk hglj khglj hkljkh gjlhkfgjflhkd gjlhk gjfhlkjhkl jhklgfjlhgfjhl dgfjhkl gjfhkl ghjklf ghjlfk jldhkgfjl ghkf ghjlfk jlghfkjlhfgkl hdjkgfl jhkfglhjgfljhgfljfgljkhfgl jkhgfljkgfl hjkl jkfglj hkl  gf lhjgf lhjkd glfhjk gfhljk gflhjkdgf lhjklhjfklk jhgflj gfl gflhjkgf hjkldgf ljkhdgf lhjkgf lhjkdg flhjkf glhjkd ghjlfd jlgfhd gfjlhd jlhgfhjld kgfhjld kgfdg fhljgj hljkgfd hjlgfkhjl kdfgjldh gfjl hdgjghlkj lhkdgfjlhk dgflhj dkgflgfjlhdg jlhkdgfhjlk djgfhl jdghlfjlfhj ghkld gdfjkgdf jldfg hjlkdgf hjlkjk hl dgfjfgjldgf jlhgf hjlkdgf jhlhjlgf jhkljlhkjl dgfljdfg lhjkdgf jklh gfjlhkdfg jlhkgdf lhjkdgjlf hk